name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Download dependencies
      run: go mod download

    - name: Check code formatting
      run: |
        if [ -n "$(gofmt -l .)" ]; then
          echo "以下のファイルはフォーマットされていません:"
          gofmt -l .
          exit 1
        fi

    - name: Check code Errors
      run: go vet ./...

    - name: Create test .env file
      run: |
        cat > .env << EOL
        DB_HOST=localhost
        DB_PORT=5432
        DB_USER=postgres
        DB_PASSWORD=postgres
        DB_NAME=postgres
        EOL

    - name: watch .env file
      run: cat .env

    - name: Run tests
      run: go test -v ./app/internal/repository/... ./app/internal/usecase/... ./app/internal/handler/...
