name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    name: Build and Push
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}

    - id: "auth"
      name: Authenticate with gcloud CLI
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: "Set up Cloud SDK"
      uses: "google-github-actions/setup-gcloud@v1"
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Configure docker to use the gcloud cli
      run: gcloud auth configure-docker --quiet

    - name: Create env file from GitHub Secrets
      run: |
        cat <<EOF > .env
        DB_HOST=${{ secrets.DB_HOST }}
        DB_USER=${{ secrets.DB_USER }}
        DB_PASSWORD=${{ secrets.DB_PASSWORD }}
        DB_NAME=${{ secrets.DB_NAME }}
        DB_PORT=${{ secrets.DB_PORT }}
        CLERK_JWKS_URL=${{ secrets.CLERK_JWKS_URL }}
        GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}
        GBIZ_API_KEY=${{ secrets.GBIZ_API_KEY }}
        EOF

    - name: Build
      run: |
        docker build -t asia.gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.SERVICE_NAME }}:${{ github.sha }} ./

    - name: Push
      run: |
        docker push asia.gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.SERVICE_NAME }}:${{ github.sha }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy ${{ secrets.SERVICE_NAME }} \
          --image asia.gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.SERVICE_NAME }}:${{ github.sha }} \
          --port 8080 \
          --project ${{ secrets.GCP_PROJECT_ID }} \
          --region asia-northeast1 \
          --platform=managed \
          --allow-unauthenticated \
          --service-account=${{ secrets.SERVICE_ACCOUNT }} \
          --quiet
